### ISSUE TITLE
桐生会は不滅なりの出現について

### ISSUE THREAD

**Issue by ayarightgreen** [Kiryu-kai/for-kiryu-kai#6]
# 問題の背景
スキップを押した際の出現文字の挙動がおかしい
# 何が問題なのか
スキップを押した際、”桐生会は不滅なり”の文字のみの出現挙動がおかしい。
スキップを押して最下部までスクロールした際、操作しなければそもそも出現してこない。
また、最下部に到達してから操作（上にスクロール）してもスキップを押してから約12秒間は出てこない。（スキップを押さない場合に該当文字が出現するまでの時間は約14秒）
逆に12秒以内に操作していたとしても、12秒後に再度スクロールしたり何らかの操作がなければ出現しない。
# 解決方法（あれば）
さらに下部のスタッフロールなどとスキップ時の設定を同じにする。

**Comment by Choco2807** [comment]
修正しました。
