### ISSUE TITLE
最下部が出現しない

### ISSUE THREAD

**Issue by ayarightgreen** [Kiryu-kai/for-kiryu-kai#7]
# 問題の背景
スキップ時の挙動
# 何が問題なのか
スキップした際、最下部がチャット欄となり、桐生会は不滅なり及びスタッフロールが出現しなくなる
# 解決方法（あれば）

**Comment by Choco2807** [comment]
修正しました。

**Comment by heppokofrontend** [comment]
@Choco2807 修正済みラベルってChocoさんが増やしてくださったのでしょうか👀

もし修正が終わっていれば、Issueを閉じていただければと思いますが
このIssueを残しておきつつ didfix で状態を表しておいて、 @ayarightgreen さんの確認待ちにしてあるということでしたこのままでOKです！

よろしくお願いします！

**Comment by Pluto-j** [comment]
同様の問題が発生したのですが環境や状況が異なります。

## 再現手順
1. モバイルモード縦画面時、ロード初期状態では「桐生会は不滅なり」以降が読み込まれない。
![2021-6-20_17-0-8](https://user-images.githubusercontent.com/73092364/122669475-85187800-d1f8-11eb-8480-99ffa94d70b9.jpg)
2. その後、画面を一度倒し横画面に変更すると該当部分が読み込まれる。
![2021-6-20_18-35-40](https://user-images.githubusercontent.com/73092364/122669568-f6582b00-d1f8-11eb-8955-0ea84f464679.jpg)

## 検証環境
* 端末 : Sony Xperia XZ3
* OS : Android 10
* Browser : Chrome Ver 91.0.4472.101

## 備考
ブラウザを「Firefox」で表示させた場合は期待通りの表示が行われるので
モバイル版Chrome固有の問題の可能性がある。
